#ifndef EVSE_BOOT_BSP__BSP_COMMON_H
#define EVSE_BOOT_BSP__BSP_COMMON_H

// tables
typedef enum {
    BSP_STATUS_OK = 0,
    BSP_STATUS_ERROR,
    BSP_STATUS_TIMEOUT,
    BSP_STATUS_BUSY,
    BSP_STATUS_INVALID_ARGUMENT,
    BSP_STATUS_NOT_INITIALIZED
} bsp_status_t;

#endif // EVSE_BOOT_BSP__BSP_COMMON_H