#ifndef EVSE_BOOT_DRIVER__DRV_COMMON_H
#define EVSE_BOOT_DRIVER__DRV_COMMON_H

// tables
typedef enum {
    DRV_STATUS_OK = 0,
    DRV_STATUS_ERROR,
    DRV_STATUS_TIMEOUT,
    DRV_STATUS_BUSY,
    DRV_STATUS_INVALID_ARGUMENT,
    DRV_STATUS_NOT_INITIALIZED
} drv_status_t;

#endif // EVSE_BOOT_DRIVER__DRV_COMMON_H